# Generated by Django 2.2.7 on 2019-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='activities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='bdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='books',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='career',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='education_form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='education_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='games',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='graduation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='hometown',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='movies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='occupation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='personal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='relation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='schools',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='tv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='university_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
